accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('date/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),


]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
path('', ArticleListView.as_view(), name='home'),


    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(),  name='list'),

    path('create/', ProjectCreateView.as_view(),  name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(),  name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list')
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family : 'NanumSquareRegular;">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align:center; margin: 2rem 0;">
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스소개</span>
    </div>

    <div style="margin-top: 1rem">
        <h6 class="pragmatic_footer_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    <!--    부트스트랩-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--    구글폰트-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <!--아이콘 -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <!--    Default Css Link-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareRegular';
            src: local('NanumSquareRegular'),
            url("{% static 'fonts/NanumSquareRegular.ttf' %}") format("opentype");
        }
         @font-face {
            font-family: 'NanumSquareLight';
            src: local('NanumSquareLight'),
            url("{% static 'fonts/NanumSquareLight.ttf' %}") format("opentype");
        }
         @font-face {
            font-family: 'NanumSquareExtraBold';
            src: local('NanumSquareExtraBold'),
            url("{% static 'fonts/NanumSquareExtraBold.ttf' %}") format("opentype");
        }
         @font-face {
            font-family: 'NanumSquareBold';
            src: local('NanumSquareBold'),
            url("{% static 'fonts/NanumSquareBold.ttf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div style="text-align:center; margin: 2rem 0;">
    <div>
        <h1 class="pragmatic_footer_logo">Pragmatic</h1>
    </div>
    <div class="pragmatic_header_navbar">
        <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
            <span>Project</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
            <span>구독</span>
        </a>
        {% if not user.is_authenticated%}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <span>login</span>
        </a>
        <a href="{% url 'accountapp:create' %}" class="pragmatic_header_nav">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>